include:
  - board: xiao_ble
    shield: dya_dash_left
  - board: xiao_ble
    shield: dya_dash_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: settings_reset
